# Deploy Static Website
# TO:   Google Cloud Platform
# FROM: Cloud Shell with doe-compose tool
# $ doe compose up
---
pip:
  install: --user
    - yamllint

builtin:
  export:
    - PATH=~/.local/bin:$PATH
    - PROJECT_ID=doe-cloud
    - PROJECT_NAME=doe-cloud
    - BILLING="00A332-38ABA6-657D6E"
    - DOMAIN_NAME=doe.cloud
  eval:
    - yamllint --config-data relaxed ./doe-compose.yml; [ $? -ne 0 ] && exit

gcloud:
  projects:
    - create $PROJECT_ID --name=$PROJECT_NAME
  config:
    - set project $PROJECT_ID
    - set compute/region us-central
    - set compute/zone us-central1-a
  beta: billing projects
    - link $PROJECT_ID --billing-account=$BILLING; [ $? -ne 0 ] && exit
#  dns:
#    - managed-zones create $PROJECT_ID --description=$PROJECT_NAME --dns-name=$DOMAIN_NAME
#    - record-sets import ./dns_records --zone $PROJECT_ID --zone-file-format

gsutil:
  mb:
    - gs://$DOMAIN_NAME
  cp:
    - ./index.html gs://$DOMAIN_NAME
    - ./get gs://$DOMAIN_NAME
  acl:
    - ch -u AllUsers:R gs://$DOMAIN_NAME/*
  web:
    - set -m index.html -e 404.html gs://$DOMAIN_NAME

...
