#!/bin/sh
set -e

# This script is meant for quick & easy install via:
#   $ curl -fsSL https://doe.cloud/get | sh

do_install()
{
    sh_c='sh -c'
#    $sh_c "curl -fsSL https://doe.cloud/get | install -m 755 doe /usr/local/bin"
    $sh_c "curl -fsSL https://raw.githubusercontent.com/itraccoons/doe/master/bin/doe | install -m 755 doe /usr/local/bin"
}

do_install