#!/bin/sh
set -e

# This script is meant for quick & easy install via:
#   $ curl -fsSL https://doe.cloud/get | sh

do_install()
{
    sh_c='sh -c'
    #https://doe.cloud/doe
    $sh_c "curl -fsSL -o doe https://raw.githubusercontent.com/itraccoons/doe/master/bin/doe | install -m 755 ./doe /usr/local/bin"
}

do_install